//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordGlobal.Rx.DAC.Query {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LordGlobal.Rx.DAC.Query.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO admin_profile(admin_id,email_id,admin_name,gender,photo) VALUES (@userId,@emailId,@adminName,@gender,@photo);.
        /// </summary>
        internal static string ADD_ADMIN_DETAILS {
            get {
                return ResourceManager.GetString("ADD_ADMIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO doctor_profile(
        ///doctor_id,
        ///doctor_name,
        ///email_id,gender,
        ///permanent_registration_number,
        ///specialist,
        ///qualification,
        ///age,
        ///clinic_address,
        ///clinic_name,
        ///phone_number,
        ///landline,
        ///city,
        ///pincode,
        ///photo)
        ///VALUES(
        ///@doctorId,
        ///@doctorName,
        ///@emailId,@gender,
        ///@regNo,
        ///@sepcialist,
        ///@qualification,
        ///@age,
        ///@clinicAddress,
        ///@clinicName,
        ///@phoneNumber,
        ///@landline,
        ///@city,
        ///@pincode,
        ///@photo);.
        /// </summary>
        internal static string ADD_DOCTOR_REGISTRATION_DATA {
            get {
                return ResourceManager.GetString("ADD_DOCTOR_REGISTRATION_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO patient_profile
        ///(doctor_id,
        ///patient_name,
        ///email_id,
        ///age,
        ///address,
        ///phone_number,
        ///marital_status,
        ///temperature,
        ///gender,
        ///weight,
        ///admit_dt_tm,
        ///bp,
        ///checked_by_doctor)
        ///VALUES
        ///(CASE (SELECT user_role FROM login_details where user_id=@loggerId) 
        ///WHEN &apos;Doctor&apos; THEN (SELECT doctor_id FROM doctor_profile WHERE doctor_id=@loggerId)
        ///WHEN &apos;Receptionist&apos; THEN (SELECT doctor_id FROM receptionist_profile WHERE receptionist_id=@loggerId)
        ///END,
        ///@patientName,
        ///@emailId,
        ///@age,
        ///@address,
        ///@phoneNo, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ADD_PATIENT_DETAILS {
            get {
                return ResourceManager.GetString("ADD_PATIENT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO receptionist_profile(receptionist_id,receptionist_name,gender,email_id,doctor_id,phone_number,photo) VALUES (@userId,@receptionistName,@gender,@email,@userId,@phoneNumber,@photo);.
        /// </summary>
        internal static string ADD_RECEPTIONIST_DETAILS {
            get {
                return ResourceManager.GetString("ADD_RECEPTIONIST_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM admin_profile WHERE admin_id=@userId.
        /// </summary>
        internal static string GET_ADMIN_PROFILE_DETAILS {
            get {
                return ResourceManager.GetString("GET_ADMIN_PROFILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM doctor_profile WHERE doctor_id=@userId.
        /// </summary>
        internal static string GET_DOCTOR_PROFILE_DETAILS {
            get {
                return ResourceManager.GetString("GET_DOCTOR_PROFILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM login_details WHERE user_name=@userName.
        /// </summary>
        internal static string GET_LOGIN_DETAILS {
            get {
                return ResourceManager.GetString("GET_LOGIN_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT md.mail_from,
        ///md.mail_to,
        ///md.mail_dt,
        ///md.message,
        ///md.status,
        ///CASE (SELECT user_role FROM login_details where user_id=md.mail_from) 
        ///WHEN &apos;Doctor&apos; THEN (SELECT doctor_name FROM doctor_profile WHERE doctor_id=md.mail_from)
        ///WHEN &apos;Admin&apos; THEN (SELECT admin_name FROM admin_profile WHERE admin_id=md.mail_from)
        ///WHEN &apos;Receptionist&apos; THEN (SELECT receptionist_name FROM receptionist_profile WHERE receptionist_id=md.mail_from)
        ///END as from_name 
        ///FROM mail_details md 
        ///WHERE mail_to=@userId.
        /// </summary>
        internal static string GET_MAIL_DETAILS {
            get {
                return ResourceManager.GetString("GET_MAIL_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM notification_details WHERE user_id=@userId.
        /// </summary>
        internal static string GET_NOTIFICATION_DETAILS {
            get {
                return ResourceManager.GetString("GET_NOTIFICATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT (SELECT COUNT(*) FROM patient_profile)as total_count,
        ///(SELECT COUNT(*) FROM patient_profile WHERE doctor_id=@doctorId) as count_by_doctor FROM patient_profile.
        /// </summary>
        internal static string GET_PATIENT_COUNT_BY_DOCTOR_ID {
            get {
                return ResourceManager.GetString("GET_PATIENT_COUNT_BY_DOCTOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM patient_profile WHERE patient_id=@patientId.
        /// </summary>
        internal static string GET_PATIENT_DETAILS {
            get {
                return ResourceManager.GetString("GET_PATIENT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM receptionist_profile WHERE receptionist_id=@userId.
        /// </summary>
        internal static string GET_RECEPTIONIST_PROFILE_DETAILS {
            get {
                return ResourceManager.GetString("GET_RECEPTIONIST_PROFILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM task_details WHERE user_id=@userId.
        /// </summary>
        internal static string GET_TASK_DETAILS {
            get {
                return ResourceManager.GetString("GET_TASK_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT user_role FROM login_details WHERE user_id=@userId.
        /// </summary>
        internal static string GET_USER_ROLE {
            get {
                return ResourceManager.GetString("GET_USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LAST_INSERT_ID() as id FROM patient_profile;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE login_details set last_login_dt_tm=@loginDateTime where user_id=@userId.
        /// </summary>
        internal static string UPDATE_LAST_LOGIN_DATE_TIME {
            get {
                return ResourceManager.GetString("UPDATE_LAST_LOGIN_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE patient_profile SET patient_name=@patientName,
        ///email_id=@emailId,
        ///age=@age,
        ///address=@address,
        ///phone_number=@phoneNo,
        ///marital_status=@maritalStatus,
        ///temperature=@temperature,
        ///gender=@gender,
        ///weight=@weight,
        ///bp=@bp,
        ///doctor_id=(
        ///CASE (SELECT user_role FROM login_details where user_id=@loggerId) 
        ///WHEN &apos;Doctor&apos; THEN (SELECT doctor_id FROM doctor_profile WHERE doctor_id=@loggerId)
        ///WHEN &apos;Receptionist&apos; THEN (SELECT doctor_id FROM receptionist_profile WHERE receptionist_id=@loggerId)
        ///END) WHERE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPDATE_PATIENT_DETAILS {
            get {
                return ResourceManager.GetString("UPDATE_PATIENT_DETAILS", resourceCulture);
            }
        }
    }
}
